services:
  qresta-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qresta-app
    restart: always
    working_dir: /var/www
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./:/var/www
      # - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./database:/var/www/database
    env_file:
      - .env
    networks:
      - hellojonathan-network

  qresta-web:
    image: nginx:alpine
    container_name: qresta-nginx
    restart: always
    ports:
      - "8084:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - hellojonathan-network
    depends_on:
      - qresta-app

  qresta-db:
    image: postgres:16-alpine
    container_name: qresta-db
    restart: always
    environment:
      - POSTGRES_DB=qresta_db
      - POSTGRES_USER=qresta
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Jakarta
    ports:
      - "0.0.0.0:5432:5432" # Pakai 0.0.0.0 agar bisa diakses dari IP 192.168.x.x
    volumes:
      # Data disimpan di folder luar agar tidak hilang saat container dihapus
      - ./docker-compose/postgres/data:/var/lib/postgresql/data
    networks:
      - hellojonathan-network

  qresta-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qresta-worker
    restart: always
    command: php artisan queue:work --tries=3
    volumes:
      - ./:/var/www
    networks:
      - hellojonathan-network
    depends_on:
      - qresta-app

  qresta-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qresta-scheduler
    restart: always
    command: sh -c "while [ true ]; do php artisan schedule:run --no-interaction & sleep 60; done"
    volumes:
      - ./:/var/www
    networks:
      - hellojonathan-network
    depends_on:
      - qresta-app

  qresta-reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qresta-reverb
    restart: always
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
    env_file:
      - .env
    networks:
      - hellojonathan-network
    depends_on:
      - qresta-app

networks:
  hellojonathan-network:
    external: true
    name: hellojonathan-network
