server {
    listen 80;
    server_name snippets-manager.hellojonathan.my.id;
    index index.php index.html;
    
    # Root harus mengarah ke folder public Laravel
    root /var/www/public;

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    client_max_body_size 20M;

    # 1. Tambahkan kompresi Gzip agar loading Livewire lebih cepat
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml outdoor/xml application/xml+rss text/javascript;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    # 2. Blokir akses langsung ke file sensitif (Database SQLite)
    location ~ /\.(?!well-known).* {
        deny all;
    }

		# 3. Optimasi Static Files (CSS/JS Tailwind)
location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|otf|ttf|svg)$ {
    # Tambahkan baris ini!
    try_files $uri $uri/ /index.php?$query_string;
    
    expires 6M;
    access_log off;
    add_header Cache-Control "public";
}


    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # Pastikan ini sesuai dengan nama service di docker-compose.yml
        fastcgi_pass snippets-manager-app:9000; 
        
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        # Tambahkan timeout agar tidak gampang 504 Gateway Timeout saat migrate berat
        fastcgi_read_timeout 300;
    }
}